<a href="https://colab.research.google.com/github/Oct-o-Dev/DL/blob/main/Keras_HyperParameter_Tuning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as numpy
import pandas as pd

In [4]:
df = pd.read_csv('/content/diabetes.csv')

In [5]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72.0,35,169.5,33.6,0.627,50,1
1,1,85,66.0,29,102.5,26.6,0.351,31,0
2,8,183,64.0,32,169.5,23.3,0.672,32,1
3,1,89,66.0,23,94.0,28.1,0.167,21,0
4,0,137,40.0,35,168.0,43.1,2.288,33,1

In [6]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.495990
BloodPressure               0.174469
SkinThickness               0.295138
Insulin                     0.377081
BMI                         0.315577
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [7]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [9]:
X.shape

(768, 8)

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [53]:
import tensorflow
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense,Dropout

In [12]:
from flax.nnx.training import optimizer
model = Sequential()
model.add(Dense(32,activation='relu',input_dim=8))
model.add(Dense(1,activation='sigmoid'))

model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [13]:
model.fit(X_train , y_train , batch_size=32 , epochs = 100 , validation_data=(X_test,y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.2769 - loss: 0.9131 - val_accuracy: 0.3052 - val_loss: 0.8354
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3127 - loss: 0.7951 - val_accuracy: 0.4091 - val_loss: 0.7385
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5261 - loss: 0.7074 - val_accuracy: 0.6364 - val_loss: 0.6639
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6531 - loss: 0.6443 - val_accuracy: 0.7013 - val_loss: 0.6092
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7003 - loss: 0.5981 - val_accuracy: 0.7532 - val_loss: 0.5665
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7199 - loss: 0.5627 - val_accuracy: 0.7792 - val_loss: 0.5330
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7362 - loss: 0.5348 - val_accuracy: 0.8247 - val_loss: 0.5064
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7541 - loss: 0.5143 - val_accuracy: 0.8182 - val_loss: 0.4865
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7704 - loss: 0.4978 - val_accuracy: 0.8182 - val_loss: 0.4699
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7704 - loss: 0.4859 - val_accuracy: 0.8182 - val_loss: 0.4570
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7785 - loss: 0.4748 - val_accuracy: 0.8117 - val_loss: 0.4444
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7850 - loss: 0.4649 - val_accuracy: 0.8182 - val_loss: 0.4354
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7866 - loss: 0.4574 - val_accuracy: 0.8247 - val_loss: 0.4269
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4505 - val_accuracy: 0.8182 - val_loss: 0.4201
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7948 - loss: 0.4446 - val_accuracy: 0.8182 - val_loss: 0.4142
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7915 - loss: 0.4391 - val_accuracy: 0.8117 - val_loss: 0.4083
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7932 - loss: 0.4346 - val_accuracy: 0.8182 - val_loss: 0.4039
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7964 - loss: 0.4302 - val_accuracy: 0.8182 - val_loss: 0.4007
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7980 - loss: 0.4266 - val_accuracy: 0.8182 - val_loss: 0.3968
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7964 - loss: 0.4230 - val_accuracy: 0.8117 - val_loss: 0.3940
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7948 - loss: 0.4199 - val_accuracy: 0.8117 - val_loss: 0.3905
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7964 - loss: 0.4170 - val_accuracy: 0.8247 - val_loss: 0.3874
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4143 - val_accuracy: 0.8247 - val_loss: 0.3854
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7964 - loss: 0.4114 - val_accuracy: 0.8182 - val_loss: 0.3834
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7980 - loss: 0.4085 - val_accuracy: 0.8247 - val_loss: 0.3805
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4058 - val_accuracy: 0.8377 - val_loss: 0.3781
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4028 - val_accuracy: 0.8377 - val_loss: 0.3769
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4002 - val_accuracy: 0.8377 - val_loss: 0.3751
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8046 - loss: 0.3976 - val_accuracy: 0.8442 - val_loss: 0.3731
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8029 - loss: 0.3952 - val_accuracy: 0.8442 - val_loss: 0.3741
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.3929 - val_accuracy: 0.8442 - val_loss: 0.3739
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8046 - loss: 0.3903 - val_accuracy: 0.8442 - val_loss: 0.3716
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8094 - loss: 0.3879 - val_accuracy: 0.8442 - val_loss: 0.3688
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8127 - loss: 0.3855 - val_accuracy: 0.8442 - val_loss: 0.3674
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8143 - loss: 0.3834 - val_accuracy: 0.8442 - val_loss: 0.3654
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8192 - loss: 0.3811 - val_accuracy: 0.8442 - val_loss: 0.3638
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8208 - loss: 0.3779 - val_accuracy: 0.8442 - val_loss: 0.3618
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8225 - loss: 0.3756 - val_accuracy: 0.8506 - val_loss: 0.3613
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8290 - loss: 0.3731 - val_accuracy: 0.8506 - val_loss: 0.3600
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8355 - loss: 0.3709 - val_accuracy: 0.8506 - val_loss: 0.3575
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8404 - loss: 0.3685 - val_accuracy: 0.8506 - val_loss: 0.3567
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8404 - loss: 0.3662 - val_accuracy: 0.8506 - val_loss: 0.3558
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8420 - loss: 0.3637 - val_accuracy: 0.8506 - val_loss: 0.3535
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8404 - loss: 0.3618 - val_accuracy: 0.8506 - val_loss: 0.3506
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8420 - loss: 0.3591 - val_accuracy: 0.8506 - val_loss: 0.3499
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8436 - loss: 0.3566 - val_accuracy: 0.8506 - val_loss: 0.3493
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8436 - loss: 0.3546 - val_accuracy: 0.8571 - val_loss: 0.3474
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8502 - loss: 0.3526 - val_accuracy: 0.8571 - val_loss: 0.3456
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8518 - loss: 0.3506 - val_accuracy: 0.8636 - val_loss: 0.3455
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8534 - loss: 0.3493 - val_accuracy: 0.8571 - val_loss: 0.3439
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8583 - loss: 0.3470 - val_accuracy: 0.8636 - val_loss: 0.3429
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8583 - loss: 0.3446 - val_accuracy: 0.8636 - val_loss: 0.3428
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8599 - loss: 0.3429 - val_accuracy: 0.8636 - val_loss: 0.3421
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8616 - loss: 0.3412 - val_accuracy: 0.8636 - val_loss: 0.3404
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8583 - loss: 0.3397 - val_accuracy: 0.8701 - val_loss: 0.3392
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8616 - loss: 0.3380 - val_accuracy: 0.8636 - val_loss: 0.3391
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8664 - loss: 0.3366 - val_accuracy: 0.8701 - val_loss: 0.3369
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8616 - loss: 0.3352 - val_accuracy: 0.8766 - val_loss: 0.3361
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8616 - loss: 0.3334 - val_accuracy: 0.8701 - val_loss: 0.3344
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8648 - loss: 0.3322 - val_accuracy: 0.8701 - val_loss: 0.3348
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8632 - loss: 0.3306 - val_accuracy: 0.8701 - val_loss: 0.3347
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8664 - loss: 0.3296 - val_accuracy: 0.8701 - val_loss: 0.3342
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8648 - loss: 0.3282 - val_accuracy: 0.8701 - val_loss: 0.3333
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8664 - loss: 0.3271 - val_accuracy: 0.8701 - val_loss: 0.3331
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8648 - loss: 0.3264 - val_accuracy: 0.8701 - val_loss: 0.3314
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8697 - loss: 0.3247 - val_accuracy: 0.8701 - val_loss: 0.3320
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.8713 - loss: 0.3237 - val_accuracy: 0.8766 - val_loss: 0.3314
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8746 - loss: 0.3222 - val_accuracy: 0.8701 - val_loss: 0.3306
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8795 - loss: 0.3212 - val_accuracy: 0.8701 - val_loss: 0.3293
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8746 - loss: 0.3203 - val_accuracy: 0.8766 - val_loss: 0.3283
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8779 - loss: 0.3192 - val_accuracy: 0.8766 - val_loss: 0.3286
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8762 - loss: 0.3186 - val_accuracy: 0.8766 - val_loss: 0.3298
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8762 - loss: 0.3177 - val_accuracy: 0.8701 - val_loss: 0.3277
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8779 - loss: 0.3169 - val_accuracy: 0.8766 - val_loss: 0.3271
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8779 - loss: 0.3162 - val_accuracy: 0.8766 - val_loss: 0.3272
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8795 - loss: 0.3159 - val_accuracy: 0.8766 - val_loss: 0.3284
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8779 - loss: 0.3144 - val_accuracy: 0.8701 - val_loss: 0.3280
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8779 - loss: 0.3138 - val_accuracy: 0.8701 - val_loss: 0.3275
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8795 - loss: 0.3137 - val_accuracy: 0.8636 - val_loss: 0.3265
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8811 - loss: 0.3124 - val_accuracy: 0.8766 - val_loss: 0.3275
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8811 - loss: 0.3115 - val_accuracy: 0.8701 - val_loss: 0.3271
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8844 - loss: 0.3110 - val_accuracy: 0.8636 - val_loss: 0.3262
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8844 - loss: 0.3100 - val_accuracy: 0.8701 - val_loss: 0.3274
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8860 - loss: 0.3098 - val_accuracy: 0.8636 - val_loss: 0.3257
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8844 - loss: 0.3092 - val_accuracy: 0.8636 - val_loss: 0.3259
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8827 - loss: 0.3084 - val_accuracy: 0.8636 - val_loss: 0.3263
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8844 - loss: 0.3080 - val_accuracy: 0.8636 - val_loss: 0.3255
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8876 - loss: 0.3070 - val_accuracy: 0.8636 - val_loss: 0.3269
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8844 - loss: 0.3066 - val_accuracy: 0.8636 - val_loss: 0.3295
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8844 - loss: 0.3066 - val_accuracy: 0.8636 - val_loss: 0.3290
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8844 - loss: 0.3055 - val_accuracy: 0.8636 - val_loss: 0.3273
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8876 - loss: 0.3052 - val_accuracy: 0.8571 - val_loss: 0.3279
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8909 - loss: 0.3047 - val_accuracy: 0.8701 - val_loss: 0.3263
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8893 - loss: 0.3038 - val_accuracy: 0.8701 - val_loss: 0.3268
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8893 - loss: 0.3033 - val_accuracy: 0.8636 - val_loss: 0.3258
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8893 - loss: 0.3029 - val_accuracy: 0.8636 - val_loss: 0.3251
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8860 - loss: 0.3027 - val_accuracy: 0.8636 - val_loss: 0.3270
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8860 - loss: 0.3020 - val_accuracy: 0.8636 - val_loss: 0.3276
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8893 - loss: 0.3016 - val_accuracy: 0.8636 - val_loss: 0.3281
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8876 - loss: 0.3010 - val_accuracy: 0.8636 - val_loss: 0.3276

In [14]:
# 1. How to select app. optimizer
# No. of nodes in a layer
# How to select no. of layer
# All in one model

In [15]:
pip install -U keras-tuner

Collecting keras-tuner
  Downloading keras_tuner-1.4.8-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: keras in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (3.13.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (26.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (2.32.4)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl.metadata (221 bytes)
Requirement already satisfied: grpcio in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (1.82.1)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (5.29.6)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio->keras-tuner) (4.16.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (3.16.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.19.1)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2026.6.17)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)
Downloading keras_tuner-1.4.8-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 kB 2.7 MB/s eta 0:00:00
Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.4.8 kt-legacy-1.0.5

In [16]:
import kerastuner as kt

/tmp/ipykernel_7053/1654478174.py:1: DeprecationWarning: `import kerastuner` is deprecated, please use `import keras_tuner`.
  import kerastuner as kt

In [17]:
def build_model(hp):

  model = Sequential()

  model.add(Dense(32,activation='relu',input_dim=8))
  model.add(Dense(1,activation='sigmoid'))

  optimizer = hp.Choice('optimizer' ,values =  ['adam' , 'sgd' , 'rmsprop' , 'adadelta'])

  model.compile(optimizer=optimizer , loss='binary_crossentropy', metrics =['accuracy'])

  return model

In [18]:
tuner = kt.RandomSearch(build_model , objective='val_accuracy' , max_trials=5)

In [19]:
tuner.search(X_train , y_train , epochs=5 , validation_data=(X_test , y_test))

Trial 3 Complete [00h 00m 04s]
val_accuracy: 0.8246753215789795

Best val_accuracy So Far: 0.8246753215789795
Total elapsed time: 00h 00m 15s

In [20]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'rmsprop'}

In [21]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [22]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [23]:
model.fit(X_train , y_train , epochs=100 , initial_epoch = 6 , validation_data=(X_test , y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.7801 - loss: 0.4605 - val_accuracy: 0.8312 - val_loss: 0.4248
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7801 - loss: 0.4463 - val_accuracy: 0.8247 - val_loss: 0.4138
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7801 - loss: 0.4381 - val_accuracy: 0.8247 - val_loss: 0.4054
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7883 - loss: 0.4317 - val_accuracy: 0.8247 - val_loss: 0.3983
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7948 - loss: 0.4264 - val_accuracy: 0.8312 - val_loss: 0.3942
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7964 - loss: 0.4225 - val_accuracy: 0.8377 - val_loss: 0.3908
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7997 - loss: 0.4185 - val_accuracy: 0.8442 - val_loss: 0.3869
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7997 - loss: 0.4151 - val_accuracy: 0.8377 - val_loss: 0.3830
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4114 - val_accuracy: 0.8377 - val_loss: 0.3800
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7997 - loss: 0.4080 - val_accuracy: 0.8377 - val_loss: 0.3777
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8029 - loss: 0.4057 - val_accuracy: 0.8377 - val_loss: 0.3753
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8062 - loss: 0.4024 - val_accuracy: 0.8377 - val_loss: 0.3738
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8062 - loss: 0.3998 - val_accuracy: 0.8442 - val_loss: 0.3719
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.3973 - val_accuracy: 0.8377 - val_loss: 0.3704
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8078 - loss: 0.3950 - val_accuracy: 0.8442 - val_loss: 0.3685
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8111 - loss: 0.3931 - val_accuracy: 0.8377 - val_loss: 0.3672
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.3906 - val_accuracy: 0.8377 - val_loss: 0.3663
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.3885 - val_accuracy: 0.8377 - val_loss: 0.3650
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8127 - loss: 0.3865 - val_accuracy: 0.8377 - val_loss: 0.3637
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8143 - loss: 0.3845 - val_accuracy: 0.8506 - val_loss: 0.3622
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8176 - loss: 0.3823 - val_accuracy: 0.8506 - val_loss: 0.3606
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8225 - loss: 0.3799 - val_accuracy: 0.8571 - val_loss: 0.3594
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8225 - loss: 0.3779 - val_accuracy: 0.8571 - val_loss: 0.3583
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8290 - loss: 0.3756 - val_accuracy: 0.8442 - val_loss: 0.3576
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8339 - loss: 0.3739 - val_accuracy: 0.8506 - val_loss: 0.3559
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8355 - loss: 0.3714 - val_accuracy: 0.8506 - val_loss: 0.3564
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8388 - loss: 0.3693 - val_accuracy: 0.8442 - val_loss: 0.3557
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8322 - loss: 0.3676 - val_accuracy: 0.8506 - val_loss: 0.3545
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8339 - loss: 0.3655 - val_accuracy: 0.8636 - val_loss: 0.3530
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8388 - loss: 0.3639 - val_accuracy: 0.8571 - val_loss: 0.3522
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8420 - loss: 0.3618 - val_accuracy: 0.8636 - val_loss: 0.3509
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8469 - loss: 0.3599 - val_accuracy: 0.8636 - val_loss: 0.3504
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8485 - loss: 0.3586 - val_accuracy: 0.8636 - val_loss: 0.3497
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8469 - loss: 0.3567 - val_accuracy: 0.8636 - val_loss: 0.3495
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8502 - loss: 0.3550 - val_accuracy: 0.8636 - val_loss: 0.3487
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8534 - loss: 0.3531 - val_accuracy: 0.8701 - val_loss: 0.3492
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8567 - loss: 0.3512 - val_accuracy: 0.8636 - val_loss: 0.3476
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8550 - loss: 0.3496 - val_accuracy: 0.8701 - val_loss: 0.3468
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8534 - loss: 0.3480 - val_accuracy: 0.8636 - val_loss: 0.3463
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8567 - loss: 0.3464 - val_accuracy: 0.8636 - val_loss: 0.3458
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8583 - loss: 0.3448 - val_accuracy: 0.8636 - val_loss: 0.3452
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8632 - loss: 0.3430 - val_accuracy: 0.8636 - val_loss: 0.3455
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8697 - loss: 0.3418 - val_accuracy: 0.8766 - val_loss: 0.3450
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8681 - loss: 0.3397 - val_accuracy: 0.8766 - val_loss: 0.3439
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8713 - loss: 0.3385 - val_accuracy: 0.8766 - val_loss: 0.3432
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8713 - loss: 0.3373 - val_accuracy: 0.8766 - val_loss: 0.3432
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8730 - loss: 0.3356 - val_accuracy: 0.8766 - val_loss: 0.3424
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8730 - loss: 0.3349 - val_accuracy: 0.8766 - val_loss: 0.3423
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8697 - loss: 0.3333 - val_accuracy: 0.8766 - val_loss: 0.3424
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8730 - loss: 0.3324 - val_accuracy: 0.8766 - val_loss: 0.3433
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8779 - loss: 0.3306 - val_accuracy: 0.8766 - val_loss: 0.3423
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8779 - loss: 0.3300 - val_accuracy: 0.8766 - val_loss: 0.3420
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8730 - loss: 0.3291 - val_accuracy: 0.8831 - val_loss: 0.3425
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8811 - loss: 0.3272 - val_accuracy: 0.8766 - val_loss: 0.3422
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8811 - loss: 0.3266 - val_accuracy: 0.8766 - val_loss: 0.3424
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8795 - loss: 0.3259 - val_accuracy: 0.8766 - val_loss: 0.3422
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8811 - loss: 0.3245 - val_accuracy: 0.8701 - val_loss: 0.3419
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8827 - loss: 0.3236 - val_accuracy: 0.8701 - val_loss: 0.3420
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8844 - loss: 0.3225 - val_accuracy: 0.8701 - val_loss: 0.3421
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8860 - loss: 0.3215 - val_accuracy: 0.8636 - val_loss: 0.3421
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8893 - loss: 0.3209 - val_accuracy: 0.8636 - val_loss: 0.3423
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8844 - loss: 0.3195 - val_accuracy: 0.8636 - val_loss: 0.3432
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8893 - loss: 0.3192 - val_accuracy: 0.8636 - val_loss: 0.3431
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8860 - loss: 0.3183 - val_accuracy: 0.8636 - val_loss: 0.3430
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8893 - loss: 0.3175 - val_accuracy: 0.8571 - val_loss: 0.3436
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8876 - loss: 0.3166 - val_accuracy: 0.8571 - val_loss: 0.3442
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8893 - loss: 0.3163 - val_accuracy: 0.8571 - val_loss: 0.3443
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8909 - loss: 0.3152 - val_accuracy: 0.8571 - val_loss: 0.3445
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8909 - loss: 0.3146 - val_accuracy: 0.8571 - val_loss: 0.3437
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8876 - loss: 0.3140 - val_accuracy: 0.8571 - val_loss: 0.3445
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8893 - loss: 0.3137 - val_accuracy: 0.8571 - val_loss: 0.3440
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8893 - loss: 0.3133 - val_accuracy: 0.8571 - val_loss: 0.3438
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8876 - loss: 0.3121 - val_accuracy: 0.8571 - val_loss: 0.3438
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8909 - loss: 0.3120 - val_accuracy: 0.8571 - val_loss: 0.3429
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8893 - loss: 0.3113 - val_accuracy: 0.8571 - val_loss: 0.3435
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8925 - loss: 0.3105 - val_accuracy: 0.8571 - val_loss: 0.3449
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8925 - loss: 0.3100 - val_accuracy: 0.8571 - val_loss: 0.3454
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8909 - loss: 0.3092 - val_accuracy: 0.8571 - val_loss: 0.3461
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8893 - loss: 0.3088 - val_accuracy: 0.8571 - val_loss: 0.3468
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8909 - loss: 0.3084 - val_accuracy: 0.8571 - val_loss: 0.3464
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8893 - loss: 0.3075 - val_accuracy: 0.8571 - val_loss: 0.3460
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8941 - loss: 0.3071 - val_accuracy: 0.8571 - val_loss: 0.3457
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8909 - loss: 0.3070 - val_accuracy: 0.8571 - val_loss: 0.3455
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8941 - loss: 0.3064 - val_accuracy: 0.8571 - val_loss: 0.3467
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8925 - loss: 0.3061 - val_accuracy: 0.8571 - val_loss: 0.3479
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8925 - loss: 0.3052 - val_accuracy: 0.8571 - val_loss: 0.3471
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8893 - loss: 0.3050 - val_accuracy: 0.8571 - val_loss: 0.3467
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8958 - loss: 0.3048 - val_accuracy: 0.8571 - val_loss: 0.3474
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8925 - loss: 0.3041 - val_accuracy: 0.8571 - val_loss: 0.3482
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8909 - loss: 0.3033 - val_accuracy: 0.8571 - val_loss: 0.3479
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8909 - loss: 0.3030 - val_accuracy: 0.8506 - val_loss: 0.3496
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8925 - loss: 0.3030 - val_accuracy: 0.8571 - val_loss: 0.3487
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8941 - loss: 0.3018 - val_accuracy: 0.8571 - val_loss: 0.3483
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8941 - loss: 0.3019 - val_accuracy: 0.8571 - val_loss: 0.3470

In [24]:
def build_model(hp):

  model = Sequential()

  units = hp.Int('units' , min_value = 8, max_value = 128,step=8)
  model.add(Dense(units= units , activation='relu', input_dim= 8))
  model.add(Dense(1 , activation='sigmoid'))

  model.compile(optimizer='rmsprop' , loss='binary_crossentropy' , metrics=['accuracy'])

  return model

In [25]:
tuner = kt.RandomSearch(build_model , objective='val_accuracy' , max_trials=5 , directory='mydir')

In [26]:
tuner.search(X_train , y_train , epochs=5 , validation_data=(X_test , y_test))

Trial 5 Complete [00h 00m 02s]
val_accuracy: 0.6688311696052551

Best val_accuracy So Far: 0.8311688303947449
Total elapsed time: 00h 00m 11s

In [27]:
tuner.get_best_hyperparameters()[0].values

{'units': 128}

In [28]:
model = tuner.get_best_models(num_models = 1)[0]

In [29]:
model.fit(X_train , y_train , epochs=100 , initial_epoch=6 , validation_data=(X_test , y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.7769 - loss: 0.4679 - val_accuracy: 0.8117 - val_loss: 0.4180
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7932 - loss: 0.4455 - val_accuracy: 0.8117 - val_loss: 0.4021
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4341 - val_accuracy: 0.8182 - val_loss: 0.3940
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4248 - val_accuracy: 0.8182 - val_loss: 0.3863
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4191 - val_accuracy: 0.8312 - val_loss: 0.3809
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4118 - val_accuracy: 0.8312 - val_loss: 0.3801
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8062 - loss: 0.4062 - val_accuracy: 0.8312 - val_loss: 0.3760
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.3999 - val_accuracy: 0.8377 - val_loss: 0.3712
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8127 - loss: 0.3949 - val_accuracy: 0.8442 - val_loss: 0.3687
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8160 - loss: 0.3890 - val_accuracy: 0.8506 - val_loss: 0.3654
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8111 - loss: 0.3836 - val_accuracy: 0.8506 - val_loss: 0.3617
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8143 - loss: 0.3777 - val_accuracy: 0.8506 - val_loss: 0.3599
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8160 - loss: 0.3731 - val_accuracy: 0.8571 - val_loss: 0.3558
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8290 - loss: 0.3681 - val_accuracy: 0.8571 - val_loss: 0.3530
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8371 - loss: 0.3632 - val_accuracy: 0.8506 - val_loss: 0.3488
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8355 - loss: 0.3601 - val_accuracy: 0.8506 - val_loss: 0.3475
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8371 - loss: 0.3552 - val_accuracy: 0.8571 - val_loss: 0.3462
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8469 - loss: 0.3517 - val_accuracy: 0.8636 - val_loss: 0.3441
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8550 - loss: 0.3475 - val_accuracy: 0.8701 - val_loss: 0.3454
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8632 - loss: 0.3436 - val_accuracy: 0.8766 - val_loss: 0.3463
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8550 - loss: 0.3416 - val_accuracy: 0.8701 - val_loss: 0.3438
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8648 - loss: 0.3388 - val_accuracy: 0.8701 - val_loss: 0.3437
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8762 - loss: 0.3352 - val_accuracy: 0.8766 - val_loss: 0.3409
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8746 - loss: 0.3326 - val_accuracy: 0.8701 - val_loss: 0.3403
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8762 - loss: 0.3304 - val_accuracy: 0.8701 - val_loss: 0.3383
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8746 - loss: 0.3282 - val_accuracy: 0.8701 - val_loss: 0.3379
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8762 - loss: 0.3259 - val_accuracy: 0.8636 - val_loss: 0.3405
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8827 - loss: 0.3238 - val_accuracy: 0.8571 - val_loss: 0.3422
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8844 - loss: 0.3221 - val_accuracy: 0.8506 - val_loss: 0.3410
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8876 - loss: 0.3198 - val_accuracy: 0.8571 - val_loss: 0.3422
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8876 - loss: 0.3180 - val_accuracy: 0.8636 - val_loss: 0.3396
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8844 - loss: 0.3166 - val_accuracy: 0.8636 - val_loss: 0.3402
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8844 - loss: 0.3144 - val_accuracy: 0.8636 - val_loss: 0.3398
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8844 - loss: 0.3128 - val_accuracy: 0.8636 - val_loss: 0.3400
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8860 - loss: 0.3114 - val_accuracy: 0.8571 - val_loss: 0.3419
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8893 - loss: 0.3104 - val_accuracy: 0.8636 - val_loss: 0.3408
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8876 - loss: 0.3087 - val_accuracy: 0.8571 - val_loss: 0.3393
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8893 - loss: 0.3075 - val_accuracy: 0.8636 - val_loss: 0.3421
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8941 - loss: 0.3070 - val_accuracy: 0.8636 - val_loss: 0.3441
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8893 - loss: 0.3053 - val_accuracy: 0.8636 - val_loss: 0.3447
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8909 - loss: 0.3050 - val_accuracy: 0.8636 - val_loss: 0.3452
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8941 - loss: 0.3036 - val_accuracy: 0.8636 - val_loss: 0.3471
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8876 - loss: 0.3028 - val_accuracy: 0.8636 - val_loss: 0.3463
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8958 - loss: 0.3018 - val_accuracy: 0.8701 - val_loss: 0.3476
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8909 - loss: 0.3006 - val_accuracy: 0.8701 - val_loss: 0.3467
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8941 - loss: 0.3004 - val_accuracy: 0.8701 - val_loss: 0.3476
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8974 - loss: 0.2988 - val_accuracy: 0.8766 - val_loss: 0.3486
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8958 - loss: 0.2988 - val_accuracy: 0.8766 - val_loss: 0.3486
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8925 - loss: 0.2984 - val_accuracy: 0.8766 - val_loss: 0.3482
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8990 - loss: 0.2968 - val_accuracy: 0.8831 - val_loss: 0.3522
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8958 - loss: 0.2962 - val_accuracy: 0.8831 - val_loss: 0.3500
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8974 - loss: 0.2947 - val_accuracy: 0.8831 - val_loss: 0.3474
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8941 - loss: 0.2949 - val_accuracy: 0.8831 - val_loss: 0.3488
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9007 - loss: 0.2938 - val_accuracy: 0.8766 - val_loss: 0.3486
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8925 - loss: 0.2928 - val_accuracy: 0.8831 - val_loss: 0.3470
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9007 - loss: 0.2920 - val_accuracy: 0.8831 - val_loss: 0.3492
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8974 - loss: 0.2922 - val_accuracy: 0.8831 - val_loss: 0.3511
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8974 - loss: 0.2907 - val_accuracy: 0.8766 - val_loss: 0.3506
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8974 - loss: 0.2903 - val_accuracy: 0.8701 - val_loss: 0.3527
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9007 - loss: 0.2898 - val_accuracy: 0.8701 - val_loss: 0.3496
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8990 - loss: 0.2890 - val_accuracy: 0.8766 - val_loss: 0.3488
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9007 - loss: 0.2890 - val_accuracy: 0.8701 - val_loss: 0.3513
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9023 - loss: 0.2873 - val_accuracy: 0.8701 - val_loss: 0.3521
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9007 - loss: 0.2874 - val_accuracy: 0.8701 - val_loss: 0.3517
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9055 - loss: 0.2862 - val_accuracy: 0.8766 - val_loss: 0.3507
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9007 - loss: 0.2854 - val_accuracy: 0.8701 - val_loss: 0.3547
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9023 - loss: 0.2852 - val_accuracy: 0.8701 - val_loss: 0.3559
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9007 - loss: 0.2844 - val_accuracy: 0.8701 - val_loss: 0.3522
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9007 - loss: 0.2842 - val_accuracy: 0.8766 - val_loss: 0.3544
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9055 - loss: 0.2827 - val_accuracy: 0.8701 - val_loss: 0.3569
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9023 - loss: 0.2822 - val_accuracy: 0.8701 - val_loss: 0.3617
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9039 - loss: 0.2821 - val_accuracy: 0.8701 - val_loss: 0.3620
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9039 - loss: 0.2810 - val_accuracy: 0.8701 - val_loss: 0.3598
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9039 - loss: 0.2810 - val_accuracy: 0.8701 - val_loss: 0.3627
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9039 - loss: 0.2805 - val_accuracy: 0.8701 - val_loss: 0.3583
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9039 - loss: 0.2794 - val_accuracy: 0.8766 - val_loss: 0.3600
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9072 - loss: 0.2781 - val_accuracy: 0.8766 - val_loss: 0.3580
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9007 - loss: 0.2783 - val_accuracy: 0.8766 - val_loss: 0.3567
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9072 - loss: 0.2779 - val_accuracy: 0.8701 - val_loss: 0.3577
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9088 - loss: 0.2777 - val_accuracy: 0.8766 - val_loss: 0.3604
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9088 - loss: 0.2759 - val_accuracy: 0.8766 - val_loss: 0.3557
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9088 - loss: 0.2765 - val_accuracy: 0.8766 - val_loss: 0.3610
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9072 - loss: 0.2745 - val_accuracy: 0.8701 - val_loss: 0.3625
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9055 - loss: 0.2763 - val_accuracy: 0.8701 - val_loss: 0.3632
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9039 - loss: 0.2744 - val_accuracy: 0.8766 - val_loss: 0.3629
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9072 - loss: 0.2737 - val_accuracy: 0.8766 - val_loss: 0.3652
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9055 - loss: 0.2733 - val_accuracy: 0.8766 - val_loss: 0.3630
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9072 - loss: 0.2724 - val_accuracy: 0.8766 - val_loss: 0.3632
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9088 - loss: 0.2718 - val_accuracy: 0.8766 - val_loss: 0.3633
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9072 - loss: 0.2713 - val_accuracy: 0.8766 - val_loss: 0.3579
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9055 - loss: 0.2716 - val_accuracy: 0.8831 - val_loss: 0.3621
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9072 - loss: 0.2703 - val_accuracy: 0.8766 - val_loss: 0.3624
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9072 - loss: 0.2705 - val_accuracy: 0.8766 - val_loss: 0.3614
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9072 - loss: 0.2699 - val_accuracy: 0.8766 - val_loss: 0.3605

In [30]:
def build_model(hp):

  model = Sequential()

  model.add(Dense(32,activation='relu',input_dim=8))


  for i in range(hp.Int('num_layers' , min_value=1 , max_value=10)):
    model.add(Dense(72,activation='relu'))


  model.add(Dense(1,activation='sigmoid'))
  model.compile(optimizer='rmsprop' , loss='binary_crossentropy' , metrics=['accuracy'])

  return model

In [32]:
tuner = kt.RandomSearch(build_model , objective='val_accuracy' , max_trials = 3)

Reloading Tuner from ./untitled_project/tuner0.json

In [36]:
tuner.search(X_train , y_train , epochs=5 , validation_data=(X_test , y_test))

In [37]:
best_hp = tuner.get_best_hyperparameters()[0]
print(f'Best Hyperparameters: {best_hp.values}')

model = tuner.get_best_models(num_models=1)[0]
model.summary()

{'optimizer': 'rmsprop'}

In [58]:
def build_model(hp):
  model = Sequential()

  for i in range(hp.Int('num_layers', min_value=1, max_value=10)):
    if i == 0:
      model.add(Dense(
          units=hp.Int('units_' + str(i), min_value=8, max_value=128, step=8),
          activation=hp.Choice('activation_' + str(i), values=['relu', 'tanh', 'sigmoid']),
          input_dim=8
      ))
      model.add(Dropout(hp.Float('dropout_' + str(i), min_value=0.1, max_value=0.9, step=0.1)))
    else:
      model.add(Dense(
          units=hp.Int('units_' + str(i), min_value=8, max_value=128, step=8),
          activation=hp.Choice('activation_' + str(i), values=['relu', 'tanh', 'sigmoid'])
      ))
      model.add(Dropout(hp.Float('dropout_' + str(i), min_value=0.1, max_value=0.9, step=0.1)))

  model.add(Dense(1, activation='sigmoid'))
  model.compile(
      optimizer=hp.Choice('optimizer', values=['rmsprop', 'adam', 'sgd', 'nadam']),
      loss='binary_crossentropy',
      metrics=['accuracy']
  )

  return model

In [59]:
tuner = kt.RandomSearch(build_model , objective = 'val_accuracy' ,
                        max_trials = 3 ,
                        directory = "mydir" ,
                        project_name = 'final')

Reloading Tuner from mydir/final/tuner0.json

In [60]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

In [61]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 7,
 'units_0': 88,
 'activation_0': 'tanh',
 'optimizer': 'rmsprop',
 'units_1': 72,
 'activation_1': 'relu',
 'units_2': 72,
 'activation_2': 'relu',
 'units_3': 8,
 'activation_3': 'relu',
 'units_4': 32,
 'activation_4': 'sigmoid',
 'units_5': 40,
 'activation_5': 'sigmoid',
 'units_6': 104,
 'activation_6': 'tanh',
 'units_7': 48,
 'activation_7': 'sigmoid',
 'units_8': 64,
 'activation_8': 'relu',
 'units_9': 128,
 'activation_9': 'sigmoid'}

In [62]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 18 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [63]:
model.fit(X_train , y_train , epochs=100 , initial_epoch=6 , validation_data=(X_test , y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - accuracy: 0.7573 - loss: 0.4763 - val_accuracy: 0.8117 - val_loss: 0.4210
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4361 - val_accuracy: 0.8377 - val_loss: 0.3962
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.4193 - val_accuracy: 0.7987 - val_loss: 0.4216
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8225 - loss: 0.4117 - val_accuracy: 0.8117 - val_loss: 0.4147
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8404 - loss: 0.4001 - val_accuracy: 0.8182 - val_loss: 0.4236
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8469 - loss: 0.3882 - val_accuracy: 0.8182 - val_loss: 0.4141
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8436 - loss: 0.3652 - val_accuracy: 0.8182 - val_loss: 0.4092
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8583 - loss: 0.3666 - val_accuracy: 0.8117 - val_loss: 0.4217
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8502 - loss: 0.3882 - val_accuracy: 0.8377 - val_loss: 0.4477
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8518 - loss: 0.3770 - val_accuracy: 0.8247 - val_loss: 0.4008
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8681 - loss: 0.3531 - val_accuracy: 0.8312 - val_loss: 0.4382
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8550 - loss: 0.3580 - val_accuracy: 0.8312 - val_loss: 0.4193
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8599 - loss: 0.3437 - val_accuracy: 0.8182 - val_loss: 0.4150
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8599 - loss: 0.3505 - val_accuracy: 0.8247 - val_loss: 0.4182
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8730 - loss: 0.3321 - val_accuracy: 0.8442 - val_loss: 0.4134
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8779 - loss: 0.3181 - val_accuracy: 0.8247 - val_loss: 0.4068
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8779 - loss: 0.3280 - val_accuracy: 0.8377 - val_loss: 0.4185
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8567 - loss: 0.3409 - val_accuracy: 0.8571 - val_loss: 0.3896
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8713 - loss: 0.3402 - val_accuracy: 0.8312 - val_loss: 0.3974
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8811 - loss: 0.3150 - val_accuracy: 0.8377 - val_loss: 0.4022
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8795 - loss: 0.3023 - val_accuracy: 0.8117 - val_loss: 0.4496
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8697 - loss: 0.3151 - val_accuracy: 0.8377 - val_loss: 0.4066
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8713 - loss: 0.3235 - val_accuracy: 0.8312 - val_loss: 0.4330
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8876 - loss: 0.3098 - val_accuracy: 0.8442 - val_loss: 0.4086
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8795 - loss: 0.3109 - val_accuracy: 0.8312 - val_loss: 0.3993
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8795 - loss: 0.3081 - val_accuracy: 0.8312 - val_loss: 0.4109
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8876 - loss: 0.3115 - val_accuracy: 0.8442 - val_loss: 0.4203
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8893 - loss: 0.3028 - val_accuracy: 0.8636 - val_loss: 0.4068
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8925 - loss: 0.2987 - val_accuracy: 0.8377 - val_loss: 0.4106
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8925 - loss: 0.3032 - val_accuracy: 0.8312 - val_loss: 0.4483
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8925 - loss: 0.2928 - val_accuracy: 0.8506 - val_loss: 0.4108
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8925 - loss: 0.2809 - val_accuracy: 0.8506 - val_loss: 0.4130
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8941 - loss: 0.2867 - val_accuracy: 0.8247 - val_loss: 0.4509
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8860 - loss: 0.2987 - val_accuracy: 0.8571 - val_loss: 0.4271
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8860 - loss: 0.2970 - val_accuracy: 0.8182 - val_loss: 0.4446
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8990 - loss: 0.2937 - val_accuracy: 0.8442 - val_loss: 0.4063
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9072 - loss: 0.2787 - val_accuracy: 0.8182 - val_loss: 0.4131
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8941 - loss: 0.2928 - val_accuracy: 0.8442 - val_loss: 0.3979
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8958 - loss: 0.2834 - val_accuracy: 0.8442 - val_loss: 0.4094
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9055 - loss: 0.2691 - val_accuracy: 0.8571 - val_loss: 0.4074
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8990 - loss: 0.2924 - val_accuracy: 0.8247 - val_loss: 0.4432
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9007 - loss: 0.2822 - val_accuracy: 0.8571 - val_loss: 0.4072
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9039 - loss: 0.2803 - val_accuracy: 0.8312 - val_loss: 0.4298
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9055 - loss: 0.2783 - val_accuracy: 0.8506 - val_loss: 0.4277
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8925 - loss: 0.2796 - val_accuracy: 0.8377 - val_loss: 0.4111
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8958 - loss: 0.2812 - val_accuracy: 0.8442 - val_loss: 0.4184
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9055 - loss: 0.2670 - val_accuracy: 0.8636 - val_loss: 0.4083
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8990 - loss: 0.2839 - val_accuracy: 0.8442 - val_loss: 0.4124
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9088 - loss: 0.2591 - val_accuracy: 0.8442 - val_loss: 0.4232
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9023 - loss: 0.2660 - val_accuracy: 0.8571 - val_loss: 0.4232
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8958 - loss: 0.2736 - val_accuracy: 0.8312 - val_loss: 0.4248
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9007 - loss: 0.2562 - val_accuracy: 0.8442 - val_loss: 0.4281
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9007 - loss: 0.2778 - val_accuracy: 0.8506 - val_loss: 0.4114
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9137 - loss: 0.2510 - val_accuracy: 0.8312 - val_loss: 0.4346
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8958 - loss: 0.2767 - val_accuracy: 0.8442 - val_loss: 0.4456
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9169 - loss: 0.2562 - val_accuracy: 0.8442 - val_loss: 0.4229
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9055 - loss: 0.2731 - val_accuracy: 0.8377 - val_loss: 0.4253
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9072 - loss: 0.2586 - val_accuracy: 0.8442 - val_loss: 0.3999
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9023 - loss: 0.2658 - val_accuracy: 0.8442 - val_loss: 0.4034
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9055 - loss: 0.2553 - val_accuracy: 0.8442 - val_loss: 0.4278
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9055 - loss: 0.2569 - val_accuracy: 0.8377 - val_loss: 0.4111
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9055 - loss: 0.2710 - val_accuracy: 0.8506 - val_loss: 0.3885
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9088 - loss: 0.2567 - val_accuracy: 0.8506 - val_loss: 0.4128
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9039 - loss: 0.2441 - val_accuracy: 0.8506 - val_loss: 0.4249
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9023 - loss: 0.2566 - val_accuracy: 0.8506 - val_loss: 0.4223
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8941 - loss: 0.2682 - val_accuracy: 0.8377 - val_loss: 0.4049
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9039 - loss: 0.2580 - val_accuracy: 0.8442 - val_loss: 0.4260
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9088 - loss: 0.2496 - val_accuracy: 0.8571 - val_loss: 0.3943
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8941 - loss: 0.2539 - val_accuracy: 0.8442 - val_loss: 0.4026
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9121 - loss: 0.2417 - val_accuracy: 0.8442 - val_loss: 0.4088
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9137 - loss: 0.2436 - val_accuracy: 0.8571 - val_loss: 0.4351
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9055 - loss: 0.2531 - val_accuracy: 0.8506 - val_loss: 0.4061
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9137 - loss: 0.2466 - val_accuracy: 0.8506 - val_loss: 0.4191
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9088 - loss: 0.2280 - val_accuracy: 0.8571 - val_loss: 0.4505
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9072 - loss: 0.2442 - val_accuracy: 0.8442 - val_loss: 0.4352
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9055 - loss: 0.2582 - val_accuracy: 0.8701 - val_loss: 0.3813
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9055 - loss: 0.2509 - val_accuracy: 0.8442 - val_loss: 0.4170
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9104 - loss: 0.2463 - val_accuracy: 0.8442 - val_loss: 0.4208
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9169 - loss: 0.2368 - val_accuracy: 0.8442 - val_loss: 0.4258
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9153 - loss: 0.2336 - val_accuracy: 0.8506 - val_loss: 0.4161
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9121 - loss: 0.2377 - val_accuracy: 0.8442 - val_loss: 0.4357
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9039 - loss: 0.2448 - val_accuracy: 0.8442 - val_loss: 0.4339
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9153 - loss: 0.2354 - val_accuracy: 0.8506 - val_loss: 0.4120
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9137 - loss: 0.2454 - val_accuracy: 0.8247 - val_loss: 0.4280
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9153 - loss: 0.2324 - val_accuracy: 0.8377 - val_loss: 0.4314
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9186 - loss: 0.2320 - val_accuracy: 0.8506 - val_loss: 0.4402
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9072 - loss: 0.2406 - val_accuracy: 0.8506 - val_loss: 0.4349
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9137 - loss: 0.2426 - val_accuracy: 0.8442 - val_loss: 0.4187
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9169 - loss: 0.2350 - val_accuracy: 0.8377 - val_loss: 0.4193
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9121 - loss: 0.2380 - val_accuracy: 0.8442 - val_loss: 0.4114
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9251 - loss: 0.2206 - val_accuracy: 0.8506 - val_loss: 0.4284
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9137 - loss: 0.2446 - val_accuracy: 0.8442 - val_loss: 0.4108
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9169 - loss: 0.2337 - val_accuracy: 0.8506 - val_loss: 0.3974
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9137 - loss: 0.2375 - val_accuracy: 0.8571 - val_loss: 0.4204